### ISSUE TITLE
执行到16.3步时提示出错

### ISSUE THREAD

**Issue by guoaen** [lewangdev/gost-install.ipynb#10]
执行到16.3步时提示出错。
首次安装并执行cloudflare-warp时，会提示接受相关条款，要按一下'y'.

-----------------
NOTICE:

Cloudflare only collects limited DNS query and traffic data (excluding payload)
that is sent to our network when you have the app enabled on your device. We
will not sell, rent, share, or otherwise disclose your personal information to
anyone, except as otherwise described in this Policy, without first providing
you with notice and the opportunity to consent. All information is handled in
accordance with our Privacy Policy.

More information is available at:
- https://www.cloudflare.com/application/terms/
- https://www.cloudflare.com/application/privacypolicy/

Accept Terms of Service and Privacy Policy? [y/N] y

Success
-----------------

**Comment by shuishuiwawa** [comment]
Maybe `warp-cli register --accept-tos` can address this issue.
