### ISSUE TITLE
Cloudflare WARP代理模式设置失败

### ISSUE THREAD

**Issue by Jasondeepny** [lewangdev/gost-install.ipynb#14]
Cloudflare WARP代理模式下 warp-cli connect status success warp-cli connect success 但是curl https://www.cloudflare.com/cdn-cgi/trace/ 结果warp=off 怎么解决

**Comment by lewangdev** [comment]
这个脚本 Cloudflare WARP 用的是 proxy 模式，而且是单独设置的端口，如前面的代码设置的GOST_WSS_PORT端口是不同的，如果要使用 warp，就用这个 GOST_WARP_WSS_PORT 定义端口，不用的话就用前面的wss端口
<img width="1347" alt="image" src="https://user-images.githubusercontent.com/1455685/229078788-bd282cc8-8557-42bd-a016-4c9371a91066.png">
如果要测试的话，这样来测试：

```sh
curl -x "socks5://127.0.0.1:40000" https://www.cloudflare.com/cdn-cgi/trace/
```
这是我的测试结果

```txt
root@racknerd-756db4:~# curl -x "socks5://127.0.0.1:40000" https://www.cloudflare.com/cdn-cgi/trace/
fl=11f583
h=www.cloudflare.com
ip=104.28.217.42
ts=1680253730.786
visit_scheme=https
uag=curl/7.74.0
colo=EWR
sliver=none
http=http/2
loc=US
tls=TLSv1.3
sni=plaintext
warp=on
gateway=off
rbi=off
kex=X25519
```
