### ISSUE TITLE
gost service 启动后似乎又停止了。

### ISSUE THREAD

**Issue by fakmalie** [lewangdev/gost-install.ipynb#18]
请教：按大佬的脚本在google上运行，到12步检查gost 状态时，显示启动失败，（12.1或者12.3运行没报错）返回：UnexpectedExit: Encountered a bad command exit code!
Command: 'systemctl status gost'
Exit code: 3
Stdout: already printed
Stderr: already printed
查询日志最后都是报错误：gost.service:start request repeated too quickly
failed with result 'exit-code'
Failed to start Gost service.

**Comment by lewangdev** [comment]
是不是端口冲突了？看样子是一直启动失败

**Comment by fakmalie** [comment]
多谢，的确是443端口似乎被占用了，已经搞定！
