### ISSUE TITLE
cf warp 后无法访问

### ISSUE THREAD

**Issue by Jasondeepny** [lewangdev/gost-install.ipynb#19]
未warp 下 mwss wss h2 都是可以通的，但是warp后无法连通

warp 正常开启:
<img width="986" alt="截屏2023-04-03 10 29 06" src="https://user-images.githubusercontent.com/37728137/229398156-e01ccc47-7156-4669-b19c-4aca522468f2.png">
端口放行:
<img width="462" alt="截屏2023-04-03 10 29 37" src="https://user-images.githubusercontent.com/37728137/229398205-c9ff391c-bf6e-460a-bd66-ebbf1a6eb0e8.png">

本地起ss:
<img width="1120" alt="截屏2023-04-03 10 37 00" src="https://user-images.githubusercontent.com/37728137/229399223-b566138f-0b7f-4a59-9866-8fec4a70c780.png">

**Comment by Jasondeepny** [comment]
域名证书为自签证书非cf 证书，开启cdn ，SSL  为Full 模式

**Comment by Jasondeepny** [comment]
docker命令  “-L wss://**@:8443?cert=/etc/letsencrypt/live/book.jasondepp.ml/fullchain.pem&key=/etc/letsencrypt/live/book.jasondepp.ml/privkey.pem&probe_resist=code:404&knock=www.google.com -F socks://localhost:40000”

**Comment by lewangdev** [comment]
看你的日志：
- vps -> warp 是通的
- local -> cf 可能没通
用浏览器打开  `https://book.jasondepp.ml:8443/ws` 看看是不是通的

**Comment by lewangdev** [comment]
使用 ip 直连 vps 的 warp 8443 端口是不是通的？另外 gost 可以配置多条 proxy chain，使用类似这样的配置：

```json
{
    "ServeNodes": [
        "wss://:443?secrets=/opt/gost/secrets.txt&cert=/opt/gost/ca.pem&key=/opt/gost/key.pem"
    ],
    "Routes": [
        {
            "ServeNodes": [
                "wss://:2083?secrets=/opt/gost/secrets.txt&cert=/opt/gost/ca.pem&key=/opt/gost/key.pem"
            ],
            "ChainNodes": [
                "socks5://127.0.0.1:40000"
            ]
        }
    ]
}
```

**Comment by Jasondeepny** [comment]
域名通的
<img width="791" alt="截屏2023-04-03 18 18 37" src="https://user-images.githubusercontent.com/37728137/229482296-aca0aaae-cf5b-42b6-bb62-b7e1e043228c.png">

ip 不通
<img width="791" alt="截屏2023-04-03 18 18 37" src="https://user-images.githubusercontent.com/37728137/229482341-3fe02b2b-61b4-465f-a342-9ba6a9c01fd2.png">

小云朵开启
![截屏2023-04-03 18 20 23](https://user-images.githubusercontent.com/37728137/229482392-09773be5-dabd-4c9c-83be-d295e6220950.png)

SSL FULL
![截屏2023-04-03 18 20 47](https://user-images.githubusercontent.com/37728137/229482457-960b433a-eec4-4e24-8405-2b0794ece29c.png)



看浏览器访问 local -> cf 可能没通
cf -> vps 可能没通
