### ISSUE TITLE
cert地址格式错误

### ISSUE THREAD

**Issue by lienzh** [lewangdev/gost-install.ipynb#2]
第七步中：
conf = dict(ServeNodes=[
        f"wss://{GOST_USERNAME}:{GOST_PASSWD}@:443?cert={GOST_HOME}/ca.pem&key={GOST_HOME}/key.pem"
    ])
似乎应该改成：
conf = dict(ServeNodes=[
        f"wss://{GOST_USERNAME}:{GOST_PASSWD}@:443?cert='{GOST_HOME}/ca.pem'&key='[{GOST_HOME}/key.pem'"
    ])

**Comment by lewangdev** [comment]
欢迎直接提 PR

**Comment by lewangdev** [comment]
我测试没有问题
