### ISSUE TITLE
浏览器访问教程里的地址后报错：JupyterLab Error

### ISSUE THREAD

**Issue by hellolufeng** [lewangdev/gost-install.ipynb#21]
JupyterLab Error
JupyterLab application assets not found in "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/share/jupyter/lab"
Please run `jupyter lab build` or use a different app directory

**Comment by lewangdev** [comment]
似乎是安装 jupyter 有问题，建议直接用下面这个，别自己安装了https://datalore.jetbrains.com/notebook/JQtV8X5iGGaNh33MHbfc8G/wlOSxnyYSq2u5TRQjJHAf1/

**Comment by lewangdev** [comment]
似乎问题已经解决
