### ISSUE TITLE
能写详细一些吗，小白真的看不懂

### ISSUE THREAD

**Issue by eutopia0921** [lewangdev/gost-install.ipynb#28]
从推上来的，折腾了一天还是一脸懵。linux上的客户端应该怎么配置，gost+cloudflare原理是什么，和wss是什么关系。

**Comment by lewangdev** [comment]
用 Linux 的话，得自己去折腾一下客户端。思路是用 iptables 做透明代理，和路由器上配置是一样的。原理是 cloudflare 可以代理 websocket 协议，这样 gost 启动一个 wss 服务，流量就可以从 cloudflare 走了

**Comment by lewangdev** [comment]
参考推友 [tjpicole](https://github.com/tjpicole) 的总结

https://twitter.com/tjpicole/status/1645738512547983360?s=20
![image](https://user-images.githubusercontent.com/1455685/231326727-10a6be9c-7b67-4063-aa8f-4167222dfad4.png)

**Comment by pepsi2222** [comment]
我搜了一下别的gost配置linux客户端的方案，他们没说要iptables做透明代理。。不太懂这一步的意义是什么。直接按路由器那个配置来的话，不work

**Comment by lewangdev** [comment]
你的路由器是什么系统，gost文档写得不够详细，如果你用的是openwrt，可以直接用passwall或者openclash插件，在路由器上把gost转成ss或者socks5就可以了
