### ISSUE TITLE
windows 配置shadowsocks gost 插件问题

### ISSUE THREAD

**Issue by wangweiomg** [lewangdev/gost-install.ipynb#3]
### 问题描述
在 windows11 系统上， 下载了 shadowsocks 并 把gost.exe 下载到 该目录并配置后，无法生效 ， 不用gost 插件却可以.

### 软件版本
系统: windows11
shadowsocks: 4.4.1.0
gost版本:  gost 2.11.5.zip

### 关键配置
gui-config.json 配置
```
"version": "4.4.1.0",
  "configs": [
    {
      "server": "localhost",
      "server_port": 1984,
      "password": "123456",
      "method": "chacha20-ietf-poly1305",
      "plugin": "gost",
      "plugin_args": "-L=ss://chacha20-ietf-poly1305:123456@:1984 -F=wss://USERNAME:PASS@DOMAIN:PORT",
      "timeout": 5,
      "warnLegacyUrl": false
    }
  ],
```
### 操作
启动 ss PAC 模式， 打不开google.com 。

### 可生效的配置:
去掉了gost插件， 并且 在windows Terminal 里启动gost 
```
.\gost.exe -L=ss://chacha20-ietf-poly1305:123456@:1984 -F=wss://USERNAME:PASS@DOMAIN:PORT
```
gui-config.json 
```

"version": "4.4.1.0",
  "configs": [
    {
      "server": "localhost",
      "server_port": 1984,
      "password": "123456",
      "method": "chacha20-ietf-poly1305",
      "plugin": "",
      "timeout": 5,
      "warnLegacyUrl": false
    }
  ],

``` 

这种方式却可以。

### 问题
如果是 ss 插件方式该如何配置呢？

![image](https://user-images.githubusercontent.com/10238628/226184032-f2b4ca68-7ba5-4b8c-be2d-e67d0871faa2.png)

**Comment by lewangdev** [comment]
4.4.1.0 用这个配置

```json
{
  "version": "4.4.1.0",
  "configs": [
    {
      "server": "150.136.252.227",
      "server_port": 443,
      "password": "123456",
      "method": "chacha20-ietf-poly1305",
      "plugin": "gost",
      "plugin_args": "-L=ss://chacha20-ietf-poly1305:123456@%SS_LOCAL_HOST%:%SS_LOCAL_PORT% -F=wss://bob:A5PUL_qqfkyj@%SS_REMOTE_HOST%:%SS_REMOTE_PORT%",
      "remarks": "DirectVPS",
      "timeout": 5,
      "warnLegacyUrl": false
    }
  ],
  "onlineConfigSource": [],
  "strategy": null,
  "index": 0,
  "global": false,
  "enabled": true,
  "shareOverLan": false,
  "firstRun": false,
  "localPort": 1081,
  "portableMode": true,
  "showPluginOutput": false,
  "pacUrl": "",
  "useOnlinePac": false,
  "secureLocalPac": true,
  "regeneratePacOnUpdate": true,
  "autoCheckUpdate": false,
  "checkPreRelease": false,
  "skippedUpdateVersion": "",
  "isVerboseLogging": true,
  "isIPv6Enabled": false,
  "generateLegacyUrl": false,
  "geositeUrl": "",
  "geositeSha256sumUrl": "",
  "geositeDirectGroups": [
    "private",
    "cn",
    "geolocation-!cn@cn"
  ],
  "geositeProxiedGroups": [
    "geolocation-!cn"
  ],
  "geositePreferDirect": false,
  "userAgent": "ShadowsocksWindows/$version",
  "logViewer": {
    "topMost": false,
    "wrapText": false,
    "toolbarShown": false,
    "Font": "Consolas, 8pt",
    "BackgroundColor": "Black",
    "TextColor": "White"
  },
  "proxy": {
    "useProxy": false,
    "proxyType": 0,
    "proxyServer": "",
    "proxyPort": 0,
    "proxyTimeout": 3,
    "useAuth": false,
    "authUser": "",
    "authPwd": ""
  },
  "hotkey": {
    "SwitchSystemProxy": "",
    "SwitchSystemProxyMode": "",
    "SwitchAllowLan": "",
    "ShowLogs": "",
    "ServerMoveUp": "",
    "ServerMoveDown": "",
    "RegHotkeysAtStartup": false
  },
  "WebProxy": {
    "_BypassOnLocal": false,
    "_ProxyAddress": "http://127.0.0.1:1081",
    "_BypassList": null,
    "_UseDefaultCredentials": false
  }
}
```

**Comment by wangweiomg** [comment]
非常感谢， 确实是我配置的不对， 不是软件的问题。
```
%SS_LOCAL_HOST%:%SS_LOCAL_PORT%
%SS_REMOTE_HOST%:%SS_REMOTE_PORT%
```
这些是固定字符串， 不是手动替换的变量，我直接把实际地址填进去了。

**Comment by lewangdev** [comment]
> 非常感谢， 确实是我配置的不对， 不是软件的问题。
> 
> ```
> %SS_LOCAL_HOST%:%SS_LOCAL_PORT%
> %SS_REMOTE_HOST%:%SS_REMOTE_PORT%
> ```
> 
> 这些是固定字符串， 不是手动替换的变量，我直接把实际地址填进去了。

是的， GOST 本身就是支持 SIP003 的

**Comment by lewangdev** [comment]
还有一个 `%SS_PLUGIN_OPTIONS%` ，可以把用户名密码放在这里，这样不用改文件，在ui上就可以了，这是配置

```json
{
  "version": "4.4.1.0",
  "configs": [
    {
      "server": "us01.bi83.link",
      "server_port": 443,
      "password": "123456",
      "method": "chacha20-ietf-poly1305",
      "plugin": "gost",
      "plugin_opts": "bob:A5PUL_qqfkyj",
      "plugin_args": "-L=ss://chacha20-ietf-poly1305:123456@%SS_LOCAL_HOST%:%SS_LOCAL_PORT% -F=wss://%SS_PLUGIN_OPTIONS%@%SS_REMOTE_HOST%:%SS_REMOTE_PORT%",
      "remarks": "CFProxy",
      "timeout": 5,
      "warnLegacyUrl": false
    },
    {
      "server": "150.136.252.227",
      "server_port": 443,
      "password": "123456",
      "method": "chacha20-ietf-poly1305",
      "plugin": "gost",
      "plugin_opts": "bob:A5PUL_qqfkyj",
      "plugin_args": "-L=ss://chacha20-ietf-poly1305:123456@%SS_LOCAL_HOST%:%SS_LOCAL_PORT% -F=wss://bob:A5PUL_qqfkyj@%SS_REMOTE_HOST%:%SS_REMOTE_PORT%",
      "remarks": "DirectVPS",
      "timeout": 5,
      "warnLegacyUrl": false
    }
  ],
  "onlineConfigSource": [],
  "strategy": null,
  "index": 0,
  "global": false,
  "enabled": true,
  "shareOverLan": false,
  "firstRun": false,
  "localPort": 1081,
  "portableMode": true,
  "showPluginOutput": false,
  "pacUrl": "",
  "useOnlinePac": false,
  "secureLocalPac": true,
  "regeneratePacOnUpdate": true,
  "autoCheckUpdate": false,
  "checkPreRelease": false,
  "skippedUpdateVersion": "",
  "isVerboseLogging": true,
  "isIPv6Enabled": false,
  "generateLegacyUrl": false,
  "geositeUrl": "",
  "geositeSha256sumUrl": "",
  "geositeDirectGroups": [
    "private",
    "cn",
    "geolocation-!cn@cn"
  ],
  "geositeProxiedGroups": [
    "geolocation-!cn"
  ],
  "geositePreferDirect": false,
  "userAgent": "ShadowsocksWindows/$version",
  "logViewer": {
    "topMost": false,
    "wrapText": false,
    "toolbarShown": false,
    "Font": "Consolas, 8pt",
    "BackgroundColor": "Black",
    "TextColor": "White"
  },
  "proxy": {
    "useProxy": false,
    "proxyType": 0,
    "proxyServer": "",
    "proxyPort": 0,
    "proxyTimeout": 3,
    "useAuth": false,
    "authUser": "",
    "authPwd": ""
  },
  "hotkey": {
    "SwitchSystemProxy": "",
    "SwitchSystemProxyMode": "",
    "SwitchAllowLan": "",
    "ShowLogs": "",
    "ServerMoveUp": "",
    "ServerMoveDown": "",
    "RegHotkeysAtStartup": false
  },
  "WebProxy": {
    "_BypassOnLocal": false,
    "_ProxyAddress": "http://127.0.0.1:1081",
    "_BypassList": null,
    "_UseDefaultCredentials": false
  }
}
```

**Comment by wangweiomg** [comment]
老铁说的很对，我也找到了文档：

[SIP003: A simplified plugin design for shadowsocks](https://shadowsocks.org/guide/sip003.html) 
 shadowsocks 文档说的很明白：

> A plugin accepts arguments through environment variables.

> a. Four MUST-HAVE environment variables are SS_REMOTE_HOST, SS_REMOTE_PORT, SS_LOCAL_HOST and SS_LOCAL_PORT. SS_REMOTE_HOST and SS_REMOTE_PORT are the hostname and port of the remote plugin service. SS_LOCAL_HOST and SS_LOCAL_PORT are the hostname and port of the local shadowsocks or plugin service.

> b. One OPTIONAL environment variable is SS_PLUGIN_OPTIONS. If a plugin requires additional arguments, like path to a config file, these arguments can be passed as extra options in a formatted string. An example is 'obfs=http;[obfs-host=www.baidu.com](http://obfs-host=www.baidu.com/)', where semicolons, equal signs and backslashes MUST be escaped with a backslash.


四个参数是必须的，  SS_PLUGIN_OPTIONS 是可选的。

**Comment by Typhonling** [comment]
以我的理解，Shadowsocks与Gost的通信到-L就结束了，-F之后与SS完全无关，因为两者之间是本地通信所以完全没必要加密，使用none或者plain即可，由于Shadowsocks Windows客户端必须填密码，所以密码随便填一个就行，不影响通信。
```
    {
      "server": "gost服务器地址",
      "server_port": gost服务器端口,
      "password": "随便填",
      "method": "none或者plain",
      "plugin": "gost",
      "plugin_opts": "gost -F参数中的用户名:密码",
      "plugin_args": "-L=ss://none@%SS_LOCAL_HOST%:%SS_LOCAL_PORT% -F=wss://%SS_PLUGIN_OPTIONS%@%SS_REMOTE_HOST%:%SS_REMOTE_PORT%",
      "remarks": "",
      "timeout": 5,
      "warnLegacyUrl": false
    },
```

**Comment by lewangdev** [comment]
> 
高手！

我有试过在服务器上（省略user/password/host/port等参数）

```json
{
  "ServeNodes": [
    "wss://:8443"
  ],
  "ChainNodes": [
    "socks5://127.0.0.1:1088"
  ],
  "Routes": [
    {
      "ServeNodes": [
        "socks5://127.0.0.1:1088"
      ]
    }
  ]
}
```

客户端这样，代理连最后一个是 socks5

```
gost -L socks5://:1080 -F wss://server_ip:8433 -F socks5://127.0.0.1:1088
```

然后 iptables 配置透明代理

**Comment by lewangdev** [comment]
> 其实以Shadowsocks插件的方式实现Gost连接可能日常使用够了但并不完美，因为SIP003不支持UDP。 这个方式也存在一定安全性问题，比如：前置的socks代理客户端没有拦截UDP，只转发了TCP数据到Shadowsocks。观看YouTube的时候，QUIC一边在撞墙，一边在跑大流量的TCP，这个特征应该很明显。
> 
> 如果要实现TCP+UDP双连接，-F最后一跳使用socks5可能是比较合理的方式，~按照文档的说法此时的转发链会自动UDP over TCP。~ 文档太简陋，要V2V3结合着看。。。根据此项目https://github.com/KANIKIG/Multi-EasyGost得到的启发，不要使用最新的2.11.5版本，会导致socks5中的UDP转发失效。 使用2.11.2即可，用V3也行，用法如下，转发链上每个-L socks5 都要加上udp=true参数：
> 
> ```
> 服务端：-L socks5://:443?udp=true
> 客户端：-L :1080?udp=true -F socks5://:server_ip:443
> ```
> 
> 使用NatTypeTester测得NAT类型为3，这点可能trojan做得比较好，听说是fullcone，我没用过。
> 
> 以我现在的实现方式举例（**省略user/password等参数**）:
> 
> ```
> Gost服务端：-L socks5+wss://:server_port?udp=ture 
> Gost客户端：-L :local_port?udp=true -F socks5+wss://server_ip:server_port?notls=ture
> （wss已经有一层tls加密，双端gost的情况下socks5会自动变为socks5+tls，所以notls=ture去掉socks5的tls加密，不清楚gost对这种情况有没有自适应机制，反正加了应该不影响wss）
> 支持UDP的socks5代理客户端：代理服务器：Gost客户端的IP/代理端口：Gost客户端的监听端口
> Gost客户端和socks5代理客户端可以同设备运行也可以不同设备上单独设置。
> ```
> 
> ```
> 举例：
> 单机运行：Windows或者Linux命令行运行：gost -L :1080?udp=true -F socks5+wss://1.2.3.4:443?notls=ture，打开socks5代理客户端，代理协议socks5，代理服务器127.0.0.1，代理端口1080。
> 分开运行：路由器Openwrt（网关地址192.168.1.1）运行：gost -L :1080?udp=true -F socks5+wss://1.2.3.4:443?notls=ture，局域网内设备安装socks5代理客户端，代理协议socks5，代理服务器192.168.1.1，代理端口1080。
> ```
> 
> 其中-L :1080等同于-L http+socks5://:1080，意味着此端口可同时代理http和socks5，具体请参考文档。

高手！

**Comment by chaoyunidea** [comment]
![图片](https://github.com/lewangdev/gost-install.ipynb/assets/17021386/17f8043d-088c-4abb-b3f4-e6fabe4f93d0)
这边shadowssocks来使用gost的时候报错 是不是要下载gost插件 什么地方可以下载啊

**Comment by Typhonling** [comment]
> ![图片](https://user-images.githubusercontent.com/17021386/260622937-17f8043d-088c-4abb-b3f4-e6fabe4f93d0.png) 这边shadowssocks来使用gost的时候报错 是不是要下载gost插件 什么地方可以下载啊

gost.exe和shadowsocks.exe在同一个目录下即可。
现在Windows后置代理客户端我推荐使用Nekoray。
