### ISSUE TITLE
warp不通

### ISSUE THREAD

**Issue by wrlm** [lewangdev/gost-install.ipynb#30]
shadowrocket配置地址为vps ip或域名都通，地址改为1.1.1.1不通
我设置的GOST_WSS_PORT=2096

访问https://域名:2096/ws 和 https://ip:2096/ws 都显示Bad Request

![Dingtalk_20230408221058](https://user-images.githubusercontent.com/18413633/230725752-5c70a9f0-dfd8-4b30-bdde-f3bb7f811b72.jpg)

**Comment by lewangdev** [comment]
显示bad request说明是ok的，客户端配置估计哪里没对

**Comment by wrlm** [comment]
我是这样配置的，地址改成1.1.1.1就不通了

![EF8473D2-A93F-481C-B8C5-66BFA9A99C70](https://user-images.githubusercontent.com/18413633/230762103-7e1fa998-1472-4406-b2ee-874f8d3600a3.jpeg)
![A8350856-22B0-43DE-9DEE-9C0AF8CD097F](https://user-images.githubusercontent.com/18413633/230762108-368d0126-2892-4827-9f09-d64285206ceb.jpeg)

**Comment by lewangdev** [comment]
看着没什么问题，电脑上能用吗
