### ISSUE TITLE
Surge配置

### ISSUE THREAD

**Issue by chandaozhao** [lewangdev/gost-install.ipynb#32]
请问在surge5中要如何配置呢？

**Comment by lewangdev** [comment]
我没有用过 surge5，刚看了一下 surge5 的[文档](https://manual.nssurge.com/book/understanding-surge/cn/#%E6%A6%82%E8%BF%B0)，了解到它支持 http,https,socks5,socks5-tls,ss,snell,vmess,trojan 这些协议。

一种方案可以用 gost 在本地或者 lan 中把 vps 的 wss 转成 surge5 支持的协议，比如这样

```
gost -L socks5://:1081 -F wss://domain:port
```

**Comment by chandaozhao** [comment]
谢谢您，我试一下
