### ISSUE TITLE
在Azure虚拟机上面安装碰到的问题，以及对应的解决方法

### ISSUE THREAD

**Issue by jianbin91** [lewangdev/gost-install.ipynb#34]
1. 在虚拟机上安装了Ubuntu操作系统（如果你用Centos，目前的脚本是不支持，需要重新创建一个虚拟机）
2. 在Colab 按照提示，因为虚拟机非root账户，所以一开始需要设置一下 USE_SUDO = True  ； 一步一步的安装下去 (因为虚拟机不支持username/password登录，所以生成一对公钥和私钥，并配置到脚本里面)
3. 安装脚本运行还是非常顺利，中间记得去 cloudfare 生成一下SSL 证书（记得先把域名转到cloudfare里面进行管理），证书的私钥类型选择ecc （详细可以参考作者的twitter），并且记得SSL/TLS 加密模式为 完全
4. 把上面的证书贴到colab脚本里面。继续下一步进行安装；整个脚本最终需要虚拟机对外开放 443 (通过cloudfare) 和 2083（vps 的ip直连） 端口。中间碰到的问题是没有正确的开放这两个端口，你配置的时候，记得用telnet 测试一下。
5. 回到客户端这边，因为我是在macos的客户端，浏览器上用 SwitchyOmega，加一个配置socks5 127.0.0.1 1086 。记得先安装ShadowsocksX-NG,启动后，再安装gost-plugin ；（配置则参考 作者的twitter）
6. 再macos下，如果要看ShadowsocksX-NG的日志，需要自己调出console，来查看。
7.  如果你要测试源服务器gost 是否正常启动,只要访问一下： https://ip:2083/ws ，界面如果出现： Bad Request 则代表成功了。
8. 最终ip直连的方式测试成功。

非常感谢作者提供的这个脚本，省去了我非常多的时间，上面是我安装过程中，一些关键点，给总结列出来，希望能够给后面需要安装碰到问题的人一些参考

 附，作者的twitter: https://twitter.com/lewangdev/status/1636768203849490433

**Comment by lewangdev** [comment]
> 1. 在虚拟机上安装了Ubuntu操作系统（如果你用Centos，目前的脚本是不支持，需要重新创建一个虚拟机）
> 2. 在Colab 按照提示，因为虚拟机非root账户，所以一开始需要设置一下 USE_SUDO = True  ； 一步一步的安装下去 (因为虚拟机不支持username/password登录，所以生成一对公钥和私钥，并配置到脚本里面)
> 3. 安装脚本运行还是非常顺利，中间记得去 cloudfare 生成一下SSL 证书（记得先把域名转到cloudfare里面进行管理），证书的私钥类型选择ecc （详细可以参考作者的twitter），并且记得SSL/TLS 加密模式为 完全
> 4. 把上面的证书贴到colab脚本里面。继续下一步进行安装；整个脚本最终需要虚拟机对外开放 443 (通过cloudfare) 和 2083（vps 的ip直连） 端口。中间碰到的问题是没有正确的开放这两个端口，你配置的时候，记得用telnet 测试一下。
> 5. 回到客户端这边，因为我是在macos的客户端，浏览器上用 SwitchyOmega，加一个配置socks5 127.0.0.1 1086 。记得先安装ShadowsocksX-NG,启动后，再安装gost-plugin ；（配置则参考 作者的twitter）
> 6. 再macos下，如果要看ShadowsocksX-NG的日志，需要自己调出console，来查看。
> 7. 如果你要测试源服务器gost 是否正常启动,只要访问一下： https://ip:2083/ws ，界面如果出现： Bad Request 则代表成功了。
> 8. 最终ip直连的方式测试成功。
> 
> 非常感谢作者提供的这个脚本，省去了我非常多的时间，上面是我安装过程中，一些关键点，给总结列出来，希望能够给后面需要安装碰到问题的人一些参考
> 
> 附，作者的twitter: https://twitter.com/lewangdev/status/1636768203849490433

对4/5 做点补充：

4. 443 和 2083 端口可以通过 cloudflare 代理，填自己的域名就是走 cloudflare 的代理，填服务器的 IP 就是直连，自己根据实际网速情况选择直连还是代理
5. SwitchyOmega 不用安装，ShadowsocksX-NG + gost-plugin 就可以了
