### ISSUE TITLE
使用CFProxy访问网页不稳定

### ISSUE THREAD

**Issue by Djackey** [lewangdev/gost-install.ipynb#35]
### 问题描述
首先非常感谢大佬提供的安装脚本，非常受用，但是在使用的过程遇到了一些问题，想请教下，我用的是 windows10系统，使用以下配置信息，利用CFProxy代理访问经常出现打不开网页的情况，过来一段时间又能访问，还有一个问题就是google每次都跳验证，按照脚本设置走wrap白名单也解决不了，另外利用DirectVPS任何网页都访问不了，查找了很多相关资料都没有解决，想请教下大佬，这个是VPS的问题还是说我设置的问题呢，打扰啦

VPS主机信息：
厂商：racknerd
LocationSan Jose, CA (Test IP: 192.210.207.88)
Operating SystemUbuntu 18.04 with Docker Preinstalled
CPU Cores1 CPU Core (Included)

### 软件版本
系统: windows10
shadowsocks: 4.4.1.0
gost版本: gost 2.11.5

### 关键配置
参考https://github.com/lewangdev/gost-install.ipynb/issues/3进行配置

**Comment by lewangdev** [comment]
直连 vps 的 ip，请问能 ping 通服务器么？

也可以通过在浏览器里面 访问这个地址来验证，看看能不能打开：

https://{your_domain}:443/ws

或者

https://{your_ip}:443/ws

**Comment by Djackey** [comment]
感谢回复
可以ping通，从ping的数据来看，丢包率和速度都还行
https://{your_domain}:443/ws、https://{your_ip}:443/ws这两个我都试了，都是显示Bad Request

**Comment by lewangdev** [comment]
显示 Bad Request 那说明都是 ok 的。

不应该有丢包，如果有丢包，说明受到了干扰吧，丢包率低于 20% 的话，可以在服务器开启 BBR 来改善。

另外可以考虑优选 Cloudflare ip，找一个您当地连接比较快的IP

https://github.com/XIU2/CloudflareSpeedTest

**Comment by Djackey** [comment]
感谢回复
优选 Cloudflare ip之后如何进行设置呢，目前还发现一个问题，CFProxy访问Google，Google貌似识别到的ip还是我racknerd主机的IP，Cloudflare 没有进行隐藏，是不是我哪里设置出了问题

**Comment by lewangdev** [comment]
参考上面的[CloudflareSpeedTest](https://github.com/XIU2/CloudflareSpeedTest)设置。
>  优选 Cloudflare ip之后如何进行设置呢


那应该是 Google 的流量没有走 warp, 添加一下 https://ipinfo.io/ ，然后访问看看 ip 有没有变化
> 目前还发现一个问题，CFProxy访问Google，Google貌似识别到的ip还是我racknerd主机的IP，Cloudflare 没有进行隐藏，是不是我哪里设置出了问题

**Comment by Djackey** [comment]
访问https://ipinfo.io/ 查看了，IP还是主机那个，没有变化，我已经按jupyter脚本第14条设置了，貌似没有生效，这个应该如何进行调整呢

**Comment by lewangdev** [comment]
你用的哪个端口？notebook 里面 443 端口是直连，2083 才走warp 的。

**Comment by Djackey** [comment]
https://{your_domain}:443/ws，https://{your_domain}:2083/ws都是显示Bad Request，说明配置应该没问题，2083是在shadowsocks中设置吗，443和2083我都在shadowsocks中试了，443能正常访问网页，2083打不开网页，另外我也用[CloudflareSpeedTest]这个工具尝试了下修改成最优IP，也打不开网页

**Comment by lewangdev** [comment]
对的，都是显示Bad Request，说明配置没问题。可以看下 2083 的日志，看看有什么线索

**Comment by Djackey** [comment]
感谢，找到问题了，是因为cloudflare-warp配置有问题，导致的Wrap访问失败，修改下文件描述符就行，具体教程参考https://github.com/lewangdev/gost-install.ipynb/issues/23

**Comment by Maxx-Yang** [comment]
> 

小白一枚，问一下大佬，这个优选IP是配置在我的电脑上呢，还是配置在VPS上面

**Comment by lewangdev** [comment]
> > 
> 
> 
> 
> 小白一枚，问一下大佬，这个优选IP是配置在我的电脑上呢，还是配置在VPS上面

自己电脑上
