### ISSUE TITLE
Cloudflare warp状态显示on，但是不起作用

### ISSUE THREAD

**Issue by Jacques-Yang** [lewangdev/gost-install.ipynb#36]
您好，我通过 curl -x "socks5://127.0.0.1:40000" https://www.cloudflare.com/cdn-cgi/trace/ 验证，结果如下：
![image](https://github.com/lewangdev/gost-install.ipynb/assets/63287297/a7704685-7d66-432c-8a9f-21150be4ef14)

我尝试访问netflix和chatgpt，都无法访问，youtube可以访问，gost服务也是正常状态。不知道是哪里出了问题，麻烦您帮我看一下，谢谢！

**Comment by lewangdev** [comment]
gost的配置贴出来看一下，不然无法判断问题在哪里

**Comment by Jacques-Yang** [comment]
gost配置如下：
<img width="1024" alt="截屏2023-05-14 22 48 51" src="https://github.com/lewangdev/gost-install.ipynb/assets/63287297/067cef66-2cd4-47c8-9312-c3e395442e9d">

**Comment by Jacques-Yang** [comment]
您好，gost配置如下：
<img width="1024" alt="截屏2023-05-14 22 48 51" src="https://github.com/lewangdev/gost-install.ipynb/assets/63287297/f4ababe5-0075-41eb-8475-f808833f0c86">

**Comment by lewangdev** [comment]
看着没有什么问题，vultr 的防火墙要打开 443/2083端口

**Comment by Jacques-Yang** [comment]
这是防火墙设置：
![image](https://github.com/lewangdev/gost-install.ipynb/assets/63287297/24af7be9-3dac-4dbc-97c8-259cd1ba04b3)
<img width="1074" alt="截屏2023-05-15 23 10 18" src="https://github.com/lewangdev/gost-install.ipynb/assets/63287297/d6a7c20f-099b-4cef-802f-47a338d3cf28">

访问chatgpt显示：
<img width="996" alt="截屏2023-05-15 23 13 18" src="https://github.com/lewangdev/gost-install.ipynb/assets/63287297/01f1bd2a-5963-4071-ae6a-b74f3489d78f">

访问Netflix显示：
<img width="901" alt="截屏2023-05-15 23 13 58" src="https://github.com/lewangdev/gost-install.ipynb/assets/63287297/ef35011d-6232-46b1-8d6d-423fe0ee7732">

可以正常访问google和youtube等。不知道哪里出了问题😭

**Comment by lewangdev** [comment]
看截图是 chatgpt 和 Netflix 不支持您的 ip，warp 和 vps 自己的 ip 都不行吗

**Comment by Jacques-Yang** [comment]
对的，我试了很多次，warp 和 vps 自己的 ip都无法访问chatgpt和Netflix ):

**Comment by lewangdev** [comment]
试试访问 https://chat.openai.com/cdn-cgi/trace 看看返回什么

也可以用这个脚本检测一下 ip 时候支持 https://github.com/missuo/OpenAI-Checker/

**Comment by Jacques-Yang** [comment]
访问https://chat.openai.com/cdn-cgi/trace 返回结果：
![image](https://github.com/lewangdev/gost-install.ipynb/assets/63287297/7cc402e8-91a7-492c-8d58-bfc31114d6cc)

使用脚本检测ip结果如下：
![image](https://github.com/lewangdev/gost-install.ipynb/assets/63287297/23094d9b-fcbb-4b17-8351-10ac37b11268)

脚本检测ip显示我的ip是可以访问chatgpt的，但是vps ip直连是无法访问的。

**Comment by lewangdev** [comment]
如果 vps ip 直连还是不行，说明 chatGPT 是 block 掉这个 ip 了，这种情况下，才需要用 warp 试试，如果都不行，那就换 ip 了。

我看不少网友说 Vultr 的 ip 是被 ChatGPT 封了，需要用 warp 试试，但是现在 warp 用的人也太多了，也会遇到 429 的问题。建议换其他家的 vps 试试

**Comment by Jacques-Yang** [comment]
谢谢您，求大佬推荐一些好用的VPS厂商 :)

**Comment by lewangdev** [comment]
参考这里 https://github.com/haoel/haoel.github.io#21-%E5%B8%B8%E8%A7%84vps

我现在用搬瓦工，hostdare 和 RackNerd

**Comment by Jacques-Yang** [comment]
好的，谢谢大佬，我买了个hostdare的，又有个问题，按照您的步骤操作下来，发现gost服务起不来 ):
![image](https://github.com/lewangdev/gost-install.ipynb/assets/63287297/77b84ab1-220d-46bb-a24e-ed2003c1c131)

好像不是端口占用的问题
![image](https://github.com/lewangdev/gost-install.ipynb/assets/63287297/76625135-644d-4992-97d6-215a14fc6d8c)

**Comment by Jacques-Yang** [comment]
已经解决了，是因为我的证书有问题导致的，换了个VPS是可以正常访问chatgpt了，感谢大佬的指导。

**Comment by lewangdev** [comment]
手动执行一下 `/opt/gost/gost -D -C /opt/gost/config.json` 看看错误日志

**Comment by Jacques-Yang** [comment]
是证书有问题导致的

**Comment by Jacques-Yang** [comment]
前面的BEGIN被去掉了，导致无法识别

**Comment by lewangdev** [comment]
> 是证书有问题导致的

我把排查问题的命令放在这里，开启 Debug 可以看到具体的错误提示

```sh
/opt/gost/gost -D -C /opt/gost/config.json
```
