### ISSUE TITLE
Gost显示407 Proxy Authentication Required错误，CFProxy无法上网

### ISSUE THREAD

**Issue by Djackey** [lewangdev/gost-install.ipynb#37]
### 问题描述
今天发现CFProxy无法上网，排查后发现Namecheap域名被暂停使用了，原因是需要进行联系人验证，按照步骤操作后域名恢复正常使用
但是连接CFProxy依然无法上网，访问https://us1.chatgptcourse.store:443/ws，https://us1.chatgptcourse.store:2083/ws都是Bad Request，应该是正常的
查看Gost日志，显示407 Proxy Authentication Required，想请教下，这种情况下问题应该如何解决呢，感谢

VPS主机信息：
厂商：racknerd
LocationSan Jose, CA
Operating SystemUbuntu 18.04 with Docker Preinstalled
CPU Cores1 CPU Core (Included)

软件版本
系统: windows10
shadowsocks: 4.4.1.0
gost版本: gost 2.11.5

**Comment by lewangdev** [comment]
密码是否填写有误：

服务器上 gost 的 secrets.txt 配置是空格
```
username passwd
```

shadowsocks 上是这样：
```
username:passwd
```

**Comment by Djackey** [comment]
找到问题了， gost 的 secrets.txt 配置用了:，改成空格重启服务就能上网了，感谢大佬
