### ISSUE TITLE
苹果小火箭节点下面有个黄色叹号-HTTP-GOST-WSS

### ISSUE THREAD

**Issue by TinyKing001** [lewangdev/gost-install.ipynb#40]
1.苹果小火箭节点下面有个黄色叹号-HTTP-GOST-WSS
2.插件gost内的 Host怎么设置
(现在是完全可以用,只是黄色叹号觉得有问题)

**Comment by lewangdev** [comment]
> 1.苹果小火箭节点下面有个黄色叹号-HTTP-GOST-WSS

我没有看过黄色叹号，方便的话，发截图看一下

> 2.插件gost内的 Host怎么设置

填自己在cloudflare上设置好的域名

**Comment by TinyKing001** [comment]
![image](https://github.com/lewangdev/gost-install.ipynb/assets/115058751/cdc7aa09-a547-4a6e-b8cc-5e72aa2d1edd)
![image](https://github.com/lewangdev/gost-install.ipynb/assets/115058751/31be9d09-2ce0-4dd5-a80d-50e41632d35a)

按照你说的，在gost插件的host位置添加us01.****.xyz以后，黄色叹号会消失，可是不再能联通。删除掉以后，叹号再次出现，能联通。

**Comment by TinyKing001** [comment]
搞好了，去掉us01就可以了

**Comment by TinyKing001** [comment]
![image](https://github.com/lewangdev/gost-install.ipynb/assets/115058751/ecc754fe-2062-4db1-95bf-199738796c2d)
![image](https://github.com/lewangdev/gost-install.ipynb/assets/115058751/e6bf98ce-ad70-446e-95a5-d2d49cce1116)
![image](https://github.com/lewangdev/gost-install.ipynb/assets/115058751/690ed098-8beb-4d2b-af08-76b7f758f9a6)
不知道为什么下午用了一下，现在打开在用又是不通，需求帮助，谢谢

**Comment by TinyKing001** [comment]
希望楼主在闲暇之余给予指导，谢谢。

**Comment by lewangdev** [comment]
把你的服务端的gost的配置的日志，客户端的配置都发出来，不然没有办法判断问题在哪里

**Comment by TinyKing001** [comment]
我并不知道什么原因，我只是记得在你的推文中曾经说过SNI是需要填写的。我把cf中的域名***.xyz填写到gost中SNI中，并且删除了gost中Host的域名，叹号消失，可以联通了。
