### ISSUE TITLE
windows下执行到第三步测试连接的时候报连接超时

### ISSUE THREAD

**Issue by chaoyunidea** [lewangdev/gost-install.ipynb#41]
python也不是太懂 按照步骤一步步来，连接不上。有没有大神指导下。
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
![图片](https://github.com/lewangdev/gost-install.ipynb/assets/17021386/a911dae8-7b17-4795-8150-2fee9be84825)

**Comment by lewangdev** [comment]
看看vps 的ip能不能ping通

**Comment by chaoyunidea** [comment]
大神你好 vps这玩意不是太懂，是要去阿里云租个服务器吧，国内的行不行，还是必须要海外的服务器。

**Comment by lewangdev** [comment]
要准备好自己的服务器才行，可以在这里买：[racknerd](https://my.racknerd.com/aff.php?aff=7453&pid=358)
