### ISSUE TITLE
GOST服务启动之后的后续步骤

### ISSUE THREAD

**Issue by chaoyunidea** [lewangdev/gost-install.ipynb#42]
![图片](https://github.com/lewangdev/gost-install.ipynb/assets/17021386/aea2c784-d5c7-4e4f-86fb-09e117825f15)
大神，gost服务视乎是启动成功了，但后续的怎么使用，可否指点一二，如何才能连上外网。

**Comment by lewangdev** [comment]
点开置顶的issue看一下，找到自己的客户端配置说明看一下

**Comment by chaoyunidea** [comment]
![图片](https://github.com/lewangdev/gost-install.ipynb/assets/17021386/270b6b71-a38f-4012-a505-46becd79c251)
这边windows使用shadowsocks连接，然后就连不上，上面是日志，下面是配置参数。
有劳大神看下哪里出问题了
```
{
  "version": "4.4.1.0",
  "configs": [
    {
      "server": "107.172.214.115",
      "server_port": 443,
      "password": "123456",
      "method": "chacha20-ietf-poly1305",
      "plugin": "gost",
      "plugin_opts": "-L=ss://chacha20-ietf-poly1305:123456@%SS_LOCAL_HOST%:%SS_LOCAL_PORT% -F=wss://username:password@%SS_REMOTE_HOST%:%SS_REMOTE_PORT%",
      "remarks": "DirectVPS",
      "timeout": 5,
      "warnLegacyUrl": false
    }
  ],
  "onlineConfigSource": [],
  "strategy": null,
  "index": 0,
  "global": false,
  "enabled": false,
  "shareOverLan": false,
  "firstRun": false,
  "localPort": 1080,
  "portableMode": true,
  "showPluginOutput": false,
  "pacUrl": "",
  "useOnlinePac": false,
  "secureLocalPac": true,
  "regeneratePacOnUpdate": true,
  "autoCheckUpdate": false,
  "checkPreRelease": false,
  "skippedUpdateVersion": "",
  "isVerboseLogging": false,
  "isIPv6Enabled": false,
  "generateLegacyUrl": false,
  "geositeUrl": "",
  "geositeSha256sumUrl": "",
  "geositeDirectGroups": [
    "private",
    "cn",
    "geolocation-!cn@cn"
  ],
  "geositeProxiedGroups": [
    "geolocation-!cn"
  ],
  "geositePreferDirect": false,
  "userAgent": "ShadowsocksWindows/$version",
  "logViewer": {
    "topMost": false,
    "wrapText": false,
    "toolbarShown": false,
    "Font": "Consolas, 8pt",
    "BackgroundColor": "Black",
    "TextColor": "White"
  },
  "proxy": {
    "useProxy": false,
    "proxyType": 0,
    "proxyServer": "",
    "proxyPort": 0,
    "proxyTimeout": 3,
    "useAuth": false,
    "authUser": "",
    "authPwd": ""
  },
  "hotkey": {
    "SwitchSystemProxy": "",
    "SwitchSystemProxyMode": "",
    "SwitchAllowLan": "",
    "ShowLogs": "",
    "ServerMoveUp": "",
    "ServerMoveDown": "",
    "RegHotkeysAtStartup": false
  },
  "WebProxy": null
}
```
![图片](https://github.com/lewangdev/gost-install.ipynb/assets/17021386/ed3a5dbc-eedc-4c1a-a422-8d2920a30211)

**Comment by lewangdev** [comment]
用自己的浏览器打开 https://107.172.214.115 看看能不能访问

**Comment by chaoyunidea** [comment]
![图片](https://github.com/lewangdev/gost-install.ipynb/assets/17021386/bba451b9-4827-40aa-943f-e8f80b301192)
浏览器访问不了啊 ping 的话可以ping通啊

**Comment by lewangdev** [comment]
防火墙  iptables 443 端口开启了吗？

**Comment by chaoyunidea** [comment]
应该开启了，之前运行过第11项。
![图片](https://github.com/lewangdev/gost-install.ipynb/assets/17021386/7c1c5b54-df0b-4eeb-a0cf-d11715b6886c)
把整个防火墙关了 外网返回500内部错误
![图片](https://github.com/lewangdev/gost-install.ipynb/assets/17021386/2e512ffd-67aa-4e67-998a-bc103fc485c3)

**Comment by lewangdev** [comment]
不是。要看下 firewalld 有没有允许 443 端口通行

**Comment by chaoyunidea** [comment]
刚刚已经打开了，可是还是连接不上。
![图片](https://github.com/lewangdev/gost-install.ipynb/assets/17021386/dcb5bb21-1c9f-4b07-be9f-95a74ec17054)

**Comment by lewangdev** [comment]
已经OK了
<img width="498" alt="image" src="https://github.com/lewangdev/gost-install.ipynb/assets/1455685/73ba38d8-cece-419d-a359-f57f790bad3e">

**Comment by chaoyunidea** [comment]
我把shadowsSocks的系统代理设为PAC模式就访问不了了
![图片](https://github.com/lewangdev/gost-install.ipynb/assets/17021386/a5200fd4-494b-441f-9268-651bc432a0c7)

**Comment by lewangdev** [comment]
> 我把shadowsSocks的系统代理设为PAC模式就访问不了了 ![图片](https://user-images.githubusercontent.com/17021386/261166091-a5200fd4-494b-441f-9268-651bc432a0c7.png)

把日志发出来，不然没法判断啥问题

**Comment by lewangdev** [comment]
问题已经解决 https://github.com/lewangdev/gost-install.ipynb/issues/43
