### ISSUE TITLE
现阶段gost的后置代理推荐Nekoray

### ISSUE THREAD

**Issue by Typhonling** [lewangdev/gost-install.ipynb#43]
Windows:https://github.com/MatsuriDayo/nekoray
macOS:https://github.com/abbasnaqdi/nekoray-macos

项目比较活跃，配置简单，路由使用geoip与geosite更全面，自定义路由也方便，且没有shadowsocks仅能使用TCP的限制。

配置：

首选项-基本设置-其他核心-添加-输入核心名（如gost）-选择gost.exe的路径，建议将gost.exe置于nekoray.exe同目录或子目录下，使用相对路径即可。
![图片](https://github.com/user-attachments/assets/7f75d7ba-4282-47f1-a778-22daa1c45fda)

服务器-手动输入配置-类型-自定义（其他核心）
名称：随意
地址&端口：留空，若需要使用其他后置代理，Nekoray的默认监听地址为127.0.0.1:2080。
核心：选择gost。
命令：gost常规命令或者使用配置文件，参考其他issues。建议使用配置文件，默认位置为config文件夹，gost命令中的‘&’连接符容易出问题不生效。
Mapping Port：无视。
Socks Port：与gost命令或配置文件中的监听端口一致。
![图片](https://github.com/user-attachments/assets/1e0fa9f2-c5d4-47ce-9a59-40d92a824262)
配置完毕。

若使用Nekoray自身进行分流，首选项-路由设置，自己配置一下。
不使用其他后置代理的话，勾选上方系统代理即可开始使用。
![image](https://github.com/lewangdev/gost-install.ipynb/assets/25653402/abdcf011-7a37-43fe-acf3-e2a49469f8e3)

Windows中如需代理无法设置代理地址的应用，可配合Netch使用，添加Socks服务器，地址127.0.0.1:2080（Nekoray默认）。

**Comment by lewangdev** [comment]
https://github.com/MatsuriDayo/nekoray

**Comment by chaoyunidea** [comment]
按上面那样配了但是页面打不开了。
另请教下，如果进行分流的话要怎么配啊。
![图片](https://github.com/lewangdev/gost-install.ipynb/assets/17021386/e2cec954-adf7-4c3e-b612-38aec8540efa)

**Comment by Typhonling** [comment]
> 按上面那样配了但是页面打不开了。 另请教下，如果进行分流的话要怎么配啊。 ![图片](https://user-images.githubusercontent.com/17021386/261190973-e2cec954-adf7-4c3e-b612-38aec8540efa.png)

Address那里就不对啊，这里留空就可以，你好像填了服务器的地址。
分流在路由设置里。我用的中文界面。

**Comment by chaoyunidea** [comment]
![图片](https://github.com/lewangdev/gost-install.ipynb/assets/17021386/649cccf2-baef-434c-b072-76551a874e85)
按照那样配了，现在是境内的可以连上，境外的不行了
谢谢大神

**Comment by Typhonling** [comment]
> ![图片](https://user-images.githubusercontent.com/17021386/261220265-649cccf2-baef-434c-b072-76551a874e85.png) 按照那样配了，现在是境内的可以连上，境外的不行了 谢谢大神

猜测服务器问题？你单独跑gost成功过吗？

**Comment by chaoyunidea** [comment]
可以了，之前是设的服务器的root账号密码，改成gost的账号密码可以连上了。
谢谢大佬
