### ISSUE TITLE
技术小白，问下这种shadowsocks+gost方式安全吗

### ISSUE THREAD

**Issue by Johnnee** [lewangdev/gost-install.ipynb#44]
感谢大佬！按照教程成功了，不过想请教下：
1 这种方式翻墙安全吗？内容会被监控吗或者很容易被人知道你浏览的内容。
2 如果是安全的，但是不在shadowsocks中设置加密算法和密码，会变得不安全吗（用了一个Andriod的gost插件，要求不在shadowsocks中设加密和密码连接）。

**Comment by lewangdev** [comment]
> 感谢大佬！按照教程成功了，不过想请教下：
> 
> 1 这种方式翻墙安全吗？内容会被监控吗或者很容易被人知道你浏览的内容。

安全的，手机上不要安装任何监控软件就行

> 2 如果是安全的，但是不在shadowsocks中设置加密算法和密码，会变得不安全吗（用了一个Andriod的gost插件，要求不在shadowsocks中设加密和密码连接）。

不影响安全，只是本机进程间通信，不设密码和加密方式这样会更省电

**Comment by Johnnee** [comment]
谢谢！
