### ISSUE TITLE
梳理了一下安卓版配置（Shadowsocks+GostPlugin）

### ISSUE THREAD

**Issue by tjpicole** [lewangdev/gost-install.ipynb#46]
根据小马哥的方案自建的代理，有时候也会稍微分享下有需要的同事朋友；之前iOS很方便，小火箭一个界面搞定；安卓呢主要也没设备，前几天升级电信宽带，送了个安卓手机，正好拿来测试安卓这边的设置，梳理了一下，供参考；
https://github.com/xausky/ShadowsocksGostPlugin/releases/download/v2.11.0/app-release.apk
https://github.com/shadowsocks/shadowsocks-android/releases/download/v5.2.6/shadowsocks--universal-v5.2.6.apk
1、安装两个程序，一个是主程序shadowsocks，版本2.11.0，一个是插件程序ShadowsocksGostPlugin，版本5.2.6；
2、小火箭配置（主程序设置）：
名称：随便取一个；
服务器设置：
服务器：123.123.123.123  #根据自身实际填写
远程端口：443    #根据自身实际填写
密码：gost   
加密方式：RC4-MD5
功能设置：
路由：GFW列表
IP6路由：默认不动
分应用VPN：默认不动
网络限制：默认不动
远程DNS：默认不动
插件：
插件：ShadowsocksGostPlugin
配置：-F wss://zhanghao:mima@#SS_HOST:#SS_PORT   #zhanghao:mima如实填写
UDP配置：默认不动

3、插件设置
设置-应用-自启动：
ShadowsocksGostPlugin 该插件程序 选择 后台自启动；
设置-应用-关联启动：
ShadowsocksGostPlugin 该插件程序 选择 开启；

**Comment by Typhonling** [comment]
安卓有一个比较复杂但自定义程度最高（不受Shadowsocks协议限制）的配法是使用terminal emulator（比如Termux） 运行gost，然后使用支持多协议的VPN软件连接gost的开放端口。
举例：Termux运行gost，监听socks5。使用Nekobox创建sock5代理连接gost。
可使用自动化解决手动输入命令与不能后台运行的问题，如使用Tasker与Termux:Tasker插件，在指定条件下（如开机启动）运行gost。

**Comment by Typhonling** [comment]
gost在某些三方程序中有个问题，对&连接符支持有问题，会直接识别为shell命令导致命令在&处被切断。如ShadowsocksGostPlugin/Termux。有条件最好使用配置文件。
ShadowsocksGostPlugin现在推荐fork的4.0，似乎解决了“&”连接符的问题。3.0.0RC有点问题，只能连域名不能连IP，4.0解决了这个问题。不过还是只能填命令，配置文件好像不行。
另外Shadowsocks除了全局和自定义路由，不在当前规则中的域名全都有DNS泄漏的问题。建议使用自定义路由，添加GFWlist之后，再添加自定义规则，规则中命中的域名只会使用远程DNS从而避免DNS泄漏。
