### ISSUE TITLE
iOS 客户端 shadowrockets 如何配置 GOST

### ISSUE THREAD

**Issue by lewangdev** [lewangdev/gost-install.ipynb#5]
## 使用 VPS 的 IP 直连

因为使用了自签证书，需要启用 Allow Inscure 

<img width="429" alt="image" src="https://user-images.githubusercontent.com/1455685/228119972-163d185b-0221-4c9b-83c2-e1d347f760bd.png">
<img width="430" alt="image" src="https://user-images.githubusercontent.com/1455685/228120013-be032958-15aa-493a-8f95-4c9141d7b5c9.png">

## 使用 Cloudflare 代理的域名

<img width="429" alt="image" src="https://user-images.githubusercontent.com/1455685/228120806-1ca67092-b9ef-4ed6-87fc-25cc94412dd6.png">
<img width="430" alt="image" src="https://user-images.githubusercontent.com/1455685/228120827-4fae5e73-b0f2-4e52-89a3-82c061e770f2.png">

**Comment by mymicroblog** [comment]
连不上啊，还套了cf的cdn。用https小火箭连接是没问题的，改cf +mwss  连不上了， 电脑用ss client可以

**Comment by lewangdev** [comment]
小火箭我用的是 wss，没测试过 mwss

**Comment by mymicroblog** [comment]
把gost->类型，改成mwss就解决了。各种试啊。这个方案我在你推上看到过 。😆
