### ISSUE TITLE
Android 客户端如何使用 GOST

### ISSUE THREAD

**Issue by lewangdev** [lewangdev/gost-install.ipynb#6]
### 搜到几个客户端项目，但是没有用过

- https://github.com/xausky/ShadowsocksGostPlugin
- https://github.com/zeromake/AnXray

### gost 的 issue
- https://github.com/ginuerzh/gost/issues/59

**Comment by lewangdev** [comment]
又找了一个：
https://github.com/segfault-bilibili/ShadowsocksGostPlugin

**Comment by Typhonling** [comment]
https://github.com/segfault-bilibili/ShadowsocksGostPlugin/releases/download/v2.11.1/app-release.apk
这一版凑合用，只能命令行。后面的GUI我一个都没试成功过

**Comment by cnscorpions** [comment]
@Typhonling 老哥，配置这个插件，一测试就抛错误 unable to resolve host, cp.cloudflare.com"

**Comment by Typhonling** [comment]
> @Typhonling 老哥，配置这个插件，一测试就抛错误 unable to resolve host, cp.cloudflare.com"

插件参数贴一下
