### ISSUE TITLE
我用了两种方式来配置,都不成功.

### ISSUE THREAD

**Issue by zhaopengme** [lewangdev/gost-install.ipynb#7]
cf工具安装 ok 的
![image](https://user-images.githubusercontent.com/1415418/228124487-d6b7da71-e585-4e8c-a93f-d903419a7f2f.png)
证书用的是CF 生成的.

1. 用https://github.com/[haoel/haoel.github.io](https://github.com/haoel/haoel.github.io#42-shadowsocks-%E5%AE%A2%E6%88%B7%E7%AB%AF)#42-shadowsocks-%E5%AE%A2%E6%88%B7%E7%AB%AF 提到的方式
操作步骤是这样的
a. 在 vps上面执行
```
# 下面的四个参数需要改成你的
DOMAIN="wss.example.com"
USER="username"
PASS="password"
PORT=8443

BIND_IP=0.0.0.0
CERT_DIR=/www/cert/wss.example.com
CERT=${CERT_DIR}/ca.pem
KEY=${CERT_DIR}/key.pem
docker run -d --name gost \
    -v ${CERT_DIR}:${CERT_DIR}:ro \
    --net=host ginuerzh/gost \
    -L "http2://${USER}:${PASS}@${BIND_IP}:8443?cert=${CERT}&key=${KEY}&probe_resist=code:404&knock=www.google.com" -F "socks://localhost:40000"
```

![image](https://user-images.githubusercontent.com/1415418/228124165-0e140346-fdf8-400e-87c1-6bef8aafe4aa.png)
b. 在本机执行 
```
gost -L ss://aes-128-cfb:123456@:1984 -F 'https://username:password@wss.example.com:8443'
```
![image](https://user-images.githubusercontent.com/1415418/228124283-6396c438-d06c-46c7-b056-0b739b016930.png)
c. 用ss工具配置
![image](https://user-images.githubusercontent.com/1415418/228124339-1d74d001-dd49-4c06-9fbf-e1bab1dccbc8.png)

2. 用你提供的 wss 的方式
就是把 ` -L "http2://${USER}:${PASS}@${BIND_IP}:8443?` 改成了 ` -L "wss://${USER}:${PASS}@${BIND_IP}:8443?`  还有
本机执行 ` gost -L ss://aes-128-cfb:123456@:1984 -F 'wss://username:password@wss.example.com:8443' ` 其他都一样

两种方式都操作,都不行,不知道为啥呢

**Comment by lewangdev** [comment]
看着配置没什么问题，防火墙端口开了吗，linux 系统的 iptables和vps服务商（如果有的话）都要把 8443 这个端口开一下

**Comment by lewangdev** [comment]
直接在浏览器里访问 https://wss.example.com:8443/ws 试试能不能访问

**Comment by Jasondeepny** [comment]
https://github.com/lewangdev/gost-install.ipynb/issues/7#issuecomment-1486190404 我也是跟上面的一样配置的，但是发现总是超时，看路由好像是没有走warp,访问我的域名发现浏览器到cf 是通的但是cf 到源服务器 是不同的，我的小云朵点亮的，SSL是Full 模式 ，不知道问题在哪里？
<img width="1122" alt="截屏2023-04-03 09 55 30" src="https://user-images.githubusercontent.com/37728137/229394362-dd29cd9e-c1ae-488e-a1c3-b6b6f0982e15.png">

**Comment by Jasondeepny** [comment]
不用warp的话wss 和 H2都是通的，但是转发走warp就不行， -L "wss://*@:8443?cert=/etc/letsencrypt/live/book.jasondepp.ml/fullchain.pem&key=/etc/letsencrypt/live/book.jasondepp.ml/privkey.pem&probe_resist=code:404&knock=www.google.com" -F "socks://localhost:40000"  ，warp也是通的

**Comment by Jasondeepny** [comment]
<img width="1218" alt="截屏2023-04-03 09 59 21" src="https://user-images.githubusercontent.com/37728137/229394815-85891653-60d9-43fc-9b89-6e7351b8a3f4.png">
